<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\YaOpt\YaOpt.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="$(RimworldVersion)" />
    <PackageReference Include="Lib.Harmony" Version="$(HarmonyVersion)" />
    <Reference Include="FacialAnimation">
      <HintPath>$([System.IO.Path]::Combine($(SteamWorkshopDirectory), 'content\294100\1635901197\$(GameVersion)\Assemblies\FacialAnimation.dll'))</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="YaOpt.Unity">
      <HintPath>$(SolutionDir)..\1.6\Assemblies\YaOpt.Unity.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetDir)$(TargetFileName)&quot; &quot;$(SolutionDir)..\1.6\Mods\Facial Animation\Assemblies\&quot; /i /y" />
  </Target>
</Project>