<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <Import Project="..\Settings.props" />
  <Import Project="..\UserSettings.props" Condition="exists('..\UserSettings.props')" />
  
  <ItemGroup>
    <ProjectReference Include="..\YaOpt\YaOpt.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0" />
    <PackageReference Include="Krafs.Rimworld.Ref" Version="$(RimworldVersion)" />
    <PackageReference Include="Lib.Harmony" Version="$(HarmonyVersion)" />
    <PackageReference Include="Zetrith.Prepatcher" Version="1.2.0" />
  </ItemGroup>
  
  <ItemGroup>
    <Publicize Include="0Harmony" />
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetDir)$(TargetFileName)&quot; &quot;$(SolutionDir)..\1.6\Prepatch\Assemblies\&quot; /i /y" />
  </Target>
</Project>