<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  
  <Import Project="..\Settings.props" />
  <Import Project="..\UserSettings.props" Condition="exists('..\UserSettings.props')" />
  
  <ItemGroup>
    <ProjectReference Include="..\YaOpt\YaOpt.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="$(RimworldVersion)" />
    <PackageReference Include="Lib.Harmony" Version="$(HarmonyVersion)" />
	<Reference Include="VEF">
      <HintPath>$([System.IO.Path]::Combine($(SteamWorkshopDirectory), 'content\294100\2023507013\1.6\Assemblies\VEF.dll'))</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetDir)$(TargetFileName)&quot; &quot;$(SolutionDir)..\1.6\Mods\Vanilla Expanded Framework\Assemblies\&quot; /i /y" />
  </Target>
</Project>